- hosts: all
  become: yes
  roles:
    - { role: base/config,     become_user: k-goda }
    - { role: base/install,    become_user: root   }
    - { role: goget/prepare,   become_user: k-goda }
    - { role: goget/install,   become_user: k-goda }
    - { role: develop/install, become_user: root   }
    - { role: develop/config,  become_user: k-goda } 
    - { role: network/install, become_user: root   }
