- name: "Include home directory vars"
  include_vars: "../../../vars/home_dir/{{ ansible_os_family }}.yml"
- name: "Include lang version vars"
  include_vars: "../../../../vars/lang_ver.yml"

- name: "Install Development Packages"
  apt:
    name: [
      "git", 
      "tig", 
      "subversion",
      "build-essential",
      "emacs-nox",
      "vim",
      "global"
    ]

#############################################
# Python
#############################################
- block:
  - name: "Install pip3"
    apt:
      name: [
        "python3-pip"
      ]
  - name: "Install iPython"
    pip:
      name: ipython
      executable: pip3
  - name: "Install virtualenv"
    pip:
      name: [
        "virtualenv",
        "virtualenvwrapper"
      ]
      executable: pip3

- block:
  - name: "Install packages for building python"
    apt:
      name: [
        "libssl-dev",
        "zlib1g-dev",
        "libbz2-dev",
        "libreadline-dev",
        "libsqlite3-dev",
        "wget",
        "curl",
        "llvm",
        "libncurses5-dev",
        "libncursesw5-dev",
        "xz-utils",
        "tk-dev",
        "libffi-dev",
        "liblzma-dev",
        "python-openssl",
        "git",
      ]

- block:
  - name: "Install Pyenv"
    git:
      repo: "https://github.com/pyenv/pyenv.git"
      dest: "{{ HOME }}/.pyenv"
  become_user: k-goda

  
