######################################################
# Install Network Packages
######################################################
- name: "Install Network Packages"
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_list:
    - "iperf"
    - "iperf3"
    - "netperf"
    - "arping"
    - "iftop"
    - "tshark"
  become_user: root

