- name: "Include vars"
  include_vars: "../../../vars/home_dir/{{ ansible_os_family }}.yml"

######################################################
# Configuration zsh
######################################################
- block:
  - name: "Clone oh-my-zsh from github"
    git:
      repo: "https://github.com/robbyrussell/oh-my-zsh.git"
      dest: "{{ HOME }}/.oh-my-zsh"
  - name: "Put .zshrc"
    copy: src=base/config/files/dot_zshrc dest="{{ HOME }}/.zshrc" force=yes backup=no

######################################################
# Configuration byobu
######################################################
- name: "Put configure files for byobu on ~/.byobu"
  copy: src=base/config/files/dot_byobu/ dest="{{ HOME }}/.byobu" force=yes backup=no

######################################################
# Configuration screen
######################################################
- name: "Put configure files for screen on ~/.screenrc"
  copy: src=base/config/files/dot_screenrc dest="{{ HOME }}/.screenrc" force=yes backup=no

######################################################
# Configuration SSH authorized key
######################################################
- block:
  - name: "Create tmp directory"
    file:
      path: "{{ HOME }}/.ansible/tmp/remote_tmp"
      state: directory
      mode: 0700
  - name: "Set authorized key from github"
    authorized_key:
      user: k-goda
      state: present
      key: https://github.com/gokzy.keys
