- name: "Include vars"
  include_vars: "../../../vars/home_dir/{{ ansible_os_family }}.yml"

######################################################
# Configuration zsh
######################################################
- block:
  - name: "Clone oh-my-zsh from github"
    git:
      repo: "https://github.com/robbyrussell/oh-my-zsh.git"
      dest: "{{ HOME }}/.oh-my-zsh"
  - name: "Clone Powerlevel9k theme"
    git:
      repo: "https://github.com/bhilburn/powerlevel9k.git"
      dest: "{{ HOME }}/.oh-my-zsh/custom/themes/powerlevel9k"
  - name: "Clone rupa/z"
    git:
      repo: "https://github.com/rupa/z"
      dest: "{{ HOME }}/.oh-my-zsh/custom/plugins/z"
  - name: "Copy peco.zsh"
    copy: src=base/config/files/peco.zsh dest="{{ HOME }}/.oh-my-zsh/custom/peco.zsh" force=yes backup=no
  - name: "Put .zshrc"
    copy: src=base/config/files/dot_zshrc dest="{{ HOME }}/.zshrc" force=yes backup=no

######################################################
# Configuration byobu
######################################################
- name: "Put configure files for byobu on ~/.byobu"
  copy: src=base/config/files/dot_byobu/ dest="{{ HOME }}/.byobu" force=yes backup=no

######################################################
# Configuration screen
######################################################
- name: "Put configure files for screen on ~/.screenrc"
  copy: src=base/config/files/dot_screenrc dest="{{ HOME }}/.screenrc" force=yes backup=no

######################################################
# Configuration SSH authorized key
######################################################
- block:
  - name: "Create tmp directory"
    file:
      path: "{{ HOME }}/.ansible/tmp/remote_tmp"
      state: directory
      mode: 0700
  - name: "Set authorized key from github"
    authorized_key:
      user: k-goda
      state: present
      key: https://github.com/gokzy.keys

######################################################
# git configuration
######################################################
- git_config: name=user.name scope=global value="GODA Kazuya"
- git_config: name=user.email scope=global value="git@gokzy.com"
- git_config: name=color.ui scope=global value=true
- git_config: name=grep.lineNumber scope=global value=true
- git_config: name=alias.find scope=global value="grep -H --heading --break"
- git_config: name=core.editor scope=global value="vi -u NONE -N"
