- name: "Include home directory vars"
  include_vars: "../../../vars/home_dir/{{ ansible_os_family }}.yml"
- name: "Include "
  include_vars: "../../../vars/lang_ver.yml"

- name: "Install Development Packages"
  homebrew:
    name: [
      "tig",
      "global",
      "emacs",
    ]
    state: present
  become_user: k-goda

- block:
  - name: "Install Python3"
    homebrew:
      name: [
        "python3"
      ]
  - name: "Install iPython"
    pip:
      name: [
        "pip",
        "ipython"
      ]
      executable: pip3
      state: latest
  - name: "Install iPython"
    pip:
      name: [
        "virtualenv",
        "virtualenvwrapper"
      ]
      executable: pip3
      state: latest
  - name: "Install Pyenv"
    git:
      repo: "https://github.com/pyenv/pyenv.git"
      dest: "{{ HOME }}/.pyenv"
  become_user: k-goda

- block:
  - name: "Install goenv"
    git:
      repo: "https://github.com/syndbg/goenv.git"
      dest:  "{{ HOME }}/.goenv"
  - name: "Create GOPATH"
    file:
      path: "{{ HOME }}/.golang"
      state: directory
  - name: "Install go {{ GO_VERSION }}"
    shell: "export GOENV_ROOT=$HOME/.goenv && export GOPATH=$HOME/.golang && PATH=$GOENV_ROOT/bin:$PATH && eval \"$(goenv init -)\" && goenv install -f {{ GO_VERSION }}"
    args:
      executable: "/usr/local/bin/zsh"
  - name: "Set global versioin"
    shell: "export GOENV_ROOT=$HOME/.goenv && export GOPATH=$HOME/.golang && PATH=$GOENV_ROOT/bin:$PATH && eval \"$(goenv init -)\" && goenv global {{ GO_VERSION }}"
    args:
      executable: "/usr/local/bin/zsh"
  become_user: k-goda

- block:
  - name: "Install ndenv"
    homebrew:
      name: [
        "ndenv",
      ]
  - name: "Instal node-build plugin"
    git:
      repo: "https://github.com/riywo/node-build.git"
      dest: "{{ HOME }}/.ndenv/plugins/node-build"
  - name: "Install node.js v{{ NODE_VERSION }} and set global"
    command: "zsh -lc \". ~/.zshrc; {{ item }}\""
    with_list:
      - "ndenv install -s v{{ NODE_VERSION }}"
      - "ndenv global v{{ NODE_VERSION }}"
  become_user: k-goda
